version: '3.8'

services:
  flutter:
    build:
      context: .
      dockerfile: Dockerfile.flutter
    volumes:
      - .:/app
    ports:
      - "80:80"  # For Flutter web server
    environment:
      - FLUTTER_DB_HOST=postgres
      - FLUTTER_DB_PORT=5432
      - FLUTTER_DB_NAME=flutter_db
      - FLUTTER_DB_USER=flutter_user
      - FLUTTER_DB_PASSWORD=flutter_pass
    depends_on:
      - database
    command: bash -c "flutter pub get && flutter run -d web-server --web-port 80 --web-hostname 0.0.0.0"
  
  database:
    container_name: database
    build:
      context: ./database
      dockerfile: database.Dockerfile
    restart: always
    ports:
      - "5432:5432"
    networks:
      - dockernetw

networks:
  dockernetw:
    driver: bridge

volumes:
  postgres_data:



